server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dockerdemodb.ckyrtu3oirai.us-east-1.rds.amazonaws.com:3306/demodb
    username: admin
    password: adminadmin

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true