server:
  port: 8080

spring:

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true

aws:
  cridentials:
    access-key-id: xxxxx
    secret-access-key: xxxxx

